pub const GTECommand = packed struct(u32) {
    GTEComm: u5 = 0b0100101,
    FakeNum: u5,
    ShiftFraction: bool,
    MultiplyMatrix: enum(u2) {
        Rotation,
        Light,
        Color,
        Reserved,
    },
    MultiplyVector: enum(u2) {
        V0,
        V1,
        V2,
        IR,
    },
    TranslationVector: enum(u2) {
        TR,
        BK,
        FC,
        None,
    },
    Zero: u2 = 0,
    GTECommand: enum(u6) {
        RTPS = 0x01,
        NCLIP = 0x06,
        OP = 0x0C,
        DPCS = 0x10,
        INTPL = 0x11,
        MVMVA = 0x12,
        NCDS = 0x13,
        CDP = 0x14,
        NCDT = 0x16,
        NCCS = 0x1B,
        CC = 0x1C,
        NCS = 0x1E,
        NCT = 0x20,
        SQR = 0x28,
        DCPL = 0x29,
        DCPT = 0x2A,
        AVSZ3 = 0x2D,
        AVSZ4 = 0x2E,
        RTPT = 0x30,
        GPF = 0x3D,
        GPL = 0x3E,
        NCCT = 0x3F,
    },
};
